config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  devise_for :users
  resources :users
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  has_many :roles
  has_many :user_metas
end

app/models/user_metum.rb
class UserMetum < ApplicationRecord
  belongs_to :user
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :role
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, avatars: []])
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.fetch(:role, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, avatars: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "RoleManagement"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"

    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") RoleManagement
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Users", users_path
            %li= link_to "Roles", roles_path

    .container
      .row
        - if user_signed_in?
          .col-sm-9
            = bootstrap_flash
            = yield
          .col-sm-3
            .well.sidebar-nav
              #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}

                %ol.carousel-indicators
                  %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
                  %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
                  %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}

                .carousel-inner
                  .item.active
                    = image_tag "image1.png", class: "d-block w-100"
                  .item
                    = image_tag "image2.png", class: "d-block w-100"

                %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic"}
                  %span.glyphicon.glyphicon-chevron-left
                %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic"}
                  %span.glyphicon.glyphicon-chevron-right
              %h3= current_user.try(:first_name)
              %ul.nav.nav-list
                %li.nav-header= current_user.try(:email)
        - else
          .col-sm-8.col-offset-2
            = bootstrap_flash
            = yield
      %footer
        %p &copy; Company 2018

app/views/roles/_form.html.haml
= form_for @role, html: { class: "form form-horizontal role" } do |f|
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), roles_path, :class => 'btn btn-default'

app/views/roles/edit.html.haml
- model_class = Role
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/roles/index.html.haml
- model_class = Role
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @roles.each do |role|
      %tr
        %td= link_to role.id, role_path(role)
        %td=l role.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), role_path(role), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_role_path(role), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), role_path(role), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_role_path, :class => 'btn btn-primary'

app/views/roles/new.html.haml
- model_class = Role
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/roles/show.html.haml
- model_class = Role
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize



= link_to t('.back', :default => t("helpers.links.back")), roles_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_role_path(@role), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), role_path(@role), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :email, class: 'control-label col-lg-2'
    .col-lg-10
      = f.email_field :email, class: 'form-control', required: true
    = f.error_span(:email)
  .form-group
    = f.label :first_name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :first_name, class: 'form-control', required: true
    = f.error_span(:first_name)
  .form-group
    = f.label :last_name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_name, class: 'form-control', required: true
    = f.error_span(:last_name)

  .form-group
    = f.label :avatars, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :avatars, multiple: true
    = f.error_span(:avatars)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:email)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td
          = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'